name: Publish
on:
  push:
    branches:
      - master 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "2.x"
      
      - name: Publish package
        run: deno publish
